version: '3.8'
services:
    ticket.disco:
        build:
            context: ./ticket.disco
        container_name: cnt_ticket.disco
        ports:
            - '6500:6500'
            # - '6501:443'
        image: img_ticket.disco

    ticket.api:
        build:
            context: ./ticket.api
        container_name: cnt_ticket.api
        ports:
            - '6100:6100'
        image: img_ticket.api
        environment:
            # override della variabile locale definita nell'application.properties'
            #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket.disco:6500/eureka
            - eureka.client.serviceUrl.defaultZone=http://ticket.disco:6500/eureka
        depends_on:
            - ticket.disco
            - ticket.tickets

    ticket.web:
        build:
            context: ./ticket.web
        container_name: cnt_ticket.web
        ports:
            - '6200:6200'
        image: img_ticket.web
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ticket.disco:6500/eureka
        depends_on:
            - ticket.disco
            - ticket.api

    ticket.tickets.db:
        build:
            context: ./ticket.tickets.db
        container_name: cnt_ticket.tickets.db
        ports:
            - '3306:3306'
        image: img_ticket.tickets.db

    ticket.tickets:
        build:
            context: ./ticket.tickets
        container_name: cnt_ticket.tickets
        ports:
            - '6300:6300'
        image: img_ticket.tickets
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ticket.disco:6500/eureka
            - SPRING_DATASOURCE_URL=jdbc:mariadb://ticket.tickets.db:3306/appticket
        depends_on:
            - ticket.disco
            - ticket.tickets.db

    ticket.user.db:
        build:
            context: ./ticket.user.db
        container_name: cnt_ticket.user.db
        ports:
            - '3307:3307'
        image: img_ticket.user.db

    ticket.user:
        build:
            context: ./ticket.user
        container_name: cnt_ticket.user
        ports:
            - '6400:6400'
        image: img_ticket.user
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ticket.disco:6500/eureka
            - SPRING_DATASOURCE_URL=jdbc:mariadb://ticket.user.db:3307/appticket
        depends_on:
            - ticket.disco
            - ticket.user.db